### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by LalatenduMohanty** [machine-drivers/docker-machine-kvm#1]
We need to update the readme with information that this repository is actually a fork and the original repository lives at https://github.com/dhiltgen/docker-machine-kvm. 

I still think it would have been good if we could have moved the original repository.

**Comment by gbraad** [comment]
@dhiltgen hasn't responded to this request... and it seems people have grown 'frustrated'. I also rather see a transfer as it preserves the issue tracker and PR proposal history.

**Comment by afbjorklund** [comment]
Maybe renaming the driver was a bit premature. Especially if it affects options/variables and stuff.
It seems to encourage the misguided notion of a "fork", when it was just supposed to be a "move".

**Comment by afbjorklund** [comment]
@LalatenduMohanty (and @gbraad) : seems like you cannot change the "parent" of a GitHub repository, maybe we should re-create `docker-machine-driver-kvm` as a real fork and retire this stand-alone repo ?

Seems like Docker is planning on keeping their `machine` and `docker-machine-kvm` around, after all...

**Comment by gbraad** [comment]
Can you show a link of this 'news' ?

And the parents was a discussion from the beginning. Are we creating or
will the KVM repo be transferred? What is the argument to recreate with
reference? We offocially got the OK to continue development, but this was
never announced from the original repo.

**Comment by afbjorklund** [comment]
I just meant we are here a year later, and it hasn't died yet. And no development has happened here ?
