### ISSUE TITLE
Incorporate changes from KVM2 driver plugin and do a release

### ISSUE THREAD

**Issue by anjannath** [machine-drivers/docker-machine-kvm#3]

**Comment by afbjorklund** [comment]
Is anybody working on this ? There are _significant_ differences between the two machine drivers...

* KVM: https://github.com/dhiltgen/docker-machine-kvm/tree/master/
  kvm,go

* KVM2: https://github.com/kubernetes/minikube/tree/master/pkg/drivers/kvm/
  domain.go  kvm.go  network.go  storage.go

If moving code over to this project, there is some separate consideration about the dependencies:

``` go
import (

        "k8s.io/minikube/pkg/minikube/config"
        "k8s.io/minikube/pkg/minikube/constants"
        "k8s.io/minikube/pkg/util"

        pkgdrivers "k8s.io/minikube/pkg/drivers"
)
```

**Comment by mheese** [comment]
and I have actually some fixes for the KVM2 driver lined up: https://github.com/kubernetes/minikube/pull/3148

If I understand the further development of this correctly, they should probably also be done against this repo?

**Comment by efrecon** [comment]
@mheese any news on the PR that you are mentioning at minikube above? I also have a slight fix on the original KVM driver so that it works as it should when docker-machine uses a relative storage path. I can't provide them right now though, since github is having a [hiccup](https://blog.github.com/2018-10-21-october21-incident-report/) today...

**Comment by efrecon** [comment]
github is slowly getting back to normal operations, you should now see my changes in this PR: #5. BTW, I agree to the above that various constants and minikube specifics needs to be removed from KVM2 when merging into KVM to be libvirt.

**Comment by mheese** [comment]
@efrecon I'm planning to work on it this week, however, there is something else that I need to finish before I can start this.

Absolutely, the driver should not hold any minikube specifics! However, I'm not so sure yet what that entails. I guess I find out this week. Depending on the outcome I might first actually draft a proposal in https://github.com/machine-drivers/discussion before I do anything else.

You should get your PR merged first imho. It's a real problem that can already be addressed.

**Comment by efrecon** [comment]
Ping here in case you start in the discussion thread, I might be able to chime in as I looked into the code today. What is the process for merging PRs?

**Comment by afbjorklund** [comment]
If not planning on doing any changes, should probably change the name back to KVM again ?

Suggest using `docker-machine-driver-kvm` rather than `docker-machine-kvm`, though...

For now, everyone is still using the binaries from the old repo:

https://github.com/dhiltgen/docker-machine-kvm/releases

**Comment by afbjorklund** [comment]
I renamed the repo, to reflect that is just a fork.
