### ISSUE TITLE
Import releases and tags from docker-machine-kvm

### ISSUE THREAD

**Issue by afbjorklund** [machine-drivers/docker-machine-kvm#4]
Currently missing the two that were *not* done on `master`:

* https://github.com/machine-drivers/docker-machine-driver-libvirt/releases/tag/v0.10.0

* https://github.com/machine-drivers/docker-machine-driver-libvirt/releases/tag/v0.8.2

* **https://github.com/dhiltgen/docker-machine-kvm/releases/tag/v0.7.0**
  https://github.com/dhiltgen/docker-machine-kvm/commit/a3882af  "Clean up logging a little"

* **https://github.com/dhiltgen/docker-machine-kvm/releases/tag/v0.6.0**
  https://github.com/dhiltgen/docker-machine-kvm/commit/8d63cea "Add disk cach/io tunables"

* https://github.com/machine-drivers/docker-machine-driver-libvirt/releases/tag/v0.5.6

* https://github.com/machine-drivers/docker-machine-driver-libvirt/releases/tag/v0.0.6

No major differences, but it would be nice to have a full import:

```
*   b14a80e (tag: v0.8.2) Merge pull request #33 from r2d4/leases
|\  
| * e5724f2 Use last entry when parsing DHCP status file
* |   dc9207e Merge pull request #34 from dongsupark/dongsu/migrate-libvirt
|\ \  
| * | a7eeb00 import libvirt/libvirt-go instead of alexzorin/libvirt-go
| |/  
* |   cd8ae9d Merge pull request #32 from caio1982/cpuhost
|\ \  
| |/  
|/|   
| * c7becbf The current domain XML used for the KVM driver does not specify a CPU mode, which makes things very slow and usually lead to a constant >25% CPU usage for people using your driver with Kubernetes and Minikube. This solves the problem as it simply tells KVM to use everything the host supports and emulate whatever else is needed.
|/  
* 37bb4cc Put NewVirConnection inside of PreCreateCheck, added error message for (#18)
* a6ecdc2 Update gitignore based on new build layout
* 7077fd0 Refactor README (#25)
*   9fb6d24 Merge pull request #22 from mikefaille/cmd-path
|\  
| * a2f0b19 FIX : Permit `go build .` to output right name
|/  
* e302cd8 Add license file
* 5f4c9b1 Add disk cach/io tunables
| * a3882af (tag: v0.7.0) Add disk cach/io tunables
| * 8d63cea (tag: v0.6.0) Clean up logging a little
|/  
* 4bc0ec9 Add a little more detail on getting started
*   c8f7e8a Merge pull request #8 from dpw/readme-quick-start
|\  
| * 28e100b Add quick start instructions
|/  
* f4dee20 (tag: v0.5.6) Merge commit '6096a1a39eb1ec6878c797b45afbe0e48410eda0' into rsampaio_conn_fix
```

Also because this version (v0.7.0) is currently being used by minishift:

https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html#setting-up-kvm-driver

* https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.7.0/docker-machine-driver-kvm

**Comment by gbraad** [comment]
You have commit rights, so you are able to push these.

**Comment by afbjorklund** [comment]
Right you are! Now it is done.
