### ISSUE TITLE
No releases?

### ISSUE THREAD

**Issue by JounQin** [machine-drivers/docker-machine-kvm#8]
https://github.com/machine-drivers/docker-machine-kvm/releases

And tags seems outdated?

https://github.com/machine-drivers/docker-machine-kvm/tags

What's the current version now?

**Comment by afbjorklund** [comment]
There are no binary releases from this project, there is only the v0.10.0:

https://github.com/dhiltgen/docker-machine-kvm/releases/tag/v0.10.0

You can build from source?

I made a patched binary here: https://github.com/afbjorklund/docker-machine-kvm/releases/tag/v0.10.0-4-gb626143

**Comment by JounQin** [comment]
I know I can build it manually from source, but without tag/release, the download would always be https://github.com/machine-drivers/docker-machine-kvm/archive/refs/heads/master.zip, I'd like to add this driver into homebrew just like https://github.com/Homebrew/homebrew-core/pull/154872

Without version, we cannot tell the difference between changes.

**Comment by JounQin** [comment]
I just found out I can use link like https://github.com/machine-drivers/docker-machine-kvm/archive/0309aae1506f88a443527a45e4da8220f4549e92.zip as version.
