### ISSUE TITLE
remame repository to `docker-machine-driver-kvm`

### ISSUE THREAD

**Issue by JounQin** [machine-drivers/docker-machine-kvm#9]

**Comment by afbjorklund** [comment]
At one point we considered renaming it (to libvirt) but at this stage, it will probably keep the name...

Docker Machine is dead, so it still needs new names to resurrect itself again. Not only the various drivers.

**Comment by JounQin** [comment]
GitHub will handle redirect correctly

**Comment by afbjorklund** [comment]
Sure, but that was not the issue with https://github.com/machine-drivers/docker-machine-driver-libvirt

Originally we thought that machine-drivers would carry on after Docker Machine, but it didn't work out.

* https://github.com/machine-drivers/discussion/issues/2

So now these repositories are just hosting the patches, for the upstream (archived) docker projects...

If it was to restart, it would need more things than just the driver (like docker-machine and boot2docker)
